[2023-10-22 06:26:43,210] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.get_rate_from_api manual__2023-10-22T06:26:41.517249+00:00 [queued]>
[2023-10-22 06:26:43,228] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.get_rate_from_api manual__2023-10-22T06:26:41.517249+00:00 [queued]>
[2023-10-22 06:26:43,230] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 06:26:43,231] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-22 06:26:43,233] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 06:26:43,254] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_rate_from_api> on 2023-10-22 06:26:41.517249+00:00
[2023-10-22 06:26:43,262] {standard_task_runner.py:52} INFO - Started process 4044 to run task
[2023-10-22 06:26:43,268] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_to_postgres', 'get_rate_from_api', 'manual__2023-10-22T06:26:41.517249+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/get_exchange_rate.py', '--cfg-path', '/tmp/tmpp1mi5s2b', '--error-file', '/tmp/tmpyjdhub0w']
[2023-10-22 06:26:43,269] {standard_task_runner.py:80} INFO - Job 15: Subtask get_rate_from_api
[2023-10-22 06:26:43,372] {task_command.py:371} INFO - Running <TaskInstance: exchange_rate_to_postgres.get_rate_from_api manual__2023-10-22T06:26:41.517249+00:00 [running]> on host 7fbc45d826e5
[2023-10-22 06:26:43,473] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=andrey
AIRFLOW_CTX_DAG_ID=exchange_rate_to_postgres
AIRFLOW_CTX_TASK_ID=get_rate_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-10-22T06:26:41.517249+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-22T06:26:41.517249+00:00
[2023-10-22 06:26:44,388] {logging_mixin.py:115} INFO - ######### datetime_rate:  1697955963
[2023-10-22 06:26:44,391] {logging_mixin.py:115} INFO - ########## value_rate:  2874442.173679
[2023-10-22 06:26:44,409] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 06:26:44,423] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_exchange_rate.py", line 35, in get_exchange_rate
    VALUES (to_timestamp({datetime_rate}), {SOURCE}, {CURRENCIES}, {value_rate})""")
psycopg2.errors.UndefinedColumn: column "btc" does not exist
LINE 2: ...                VALUES (to_timestamp(1697955963), BTC, RUB, ...
                                                             ^

[2023-10-22 06:26:44,440] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_to_***, task_id=get_rate_from_api, execution_date=20231022T062641, start_date=20231022T062643, end_date=20231022T062644
[2023-10-22 06:26:44,457] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task get_rate_from_api (column "btc" does not exist
LINE 2: ...                VALUES (to_timestamp(1697955963), BTC, RUB, ...
                                                             ^
; 4044)
[2023-10-22 06:26:44,507] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-22 06:26:44,577] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
